/**
 * The read-only allowlist runs unprompted in every mode, so each listed binary may only
 * pass in a form that neither writes nor executes. These are the argument shapes that
 * turned a listed binary into a writer or a launcher.
 */
import { describe, expect, it } from "vitest";
import { isSafeCommand } from "../ext/permissions/safe-command.ts";

describe("safe list: argument forms that execute or write", () => {
	it.each([
		"fd -x ./run.sh",
		"fd -X ./run.sh",
		"fd -Hx sh -c id",
		"fd --exec ./run.sh {}",
		"fd --exec-batch ./run.sh",
		"find . -ok ./run.sh {} ;",
		"find . -okdir ./run.sh {} ;",
		"rg --pre ./run.sh foo",
		"rg --pre=./run.sh foo",
		"sort -o package.json x",
		"sort -uo package.json x",
		"sort --output=package.json x",
		"sort --compress-program=./run.sh x",
		"tree -o out.txt",
		"git remote add evil https://x",
		"git remote set-url origin https://evil",
		"git remote remove origin",
		"git remote rename origin x",
		"git remote prune origin",
		"git remote update",
		"git branch evil",
		"git branch -m main x",
		"git branch -f main HEAD~3",
		"git branch -u origin/x",
		"git branch --unset-upstream",
		"git branch --edit-description",
		"git diff --output=package.json",
		"git diff --output package.json",
		"git log -p --output=x",
		"sed -n 'e ./run.sh' x",
		"sed -n '1e ./run.sh' x",
		"sed -n '/foo/e ./run.sh' x",
		"sed -n 's/a/b/e' x",
		"sed -n 's|a|./run.sh|pe' x",
		"sed -n -e p -e 'e ./run.sh' x",
		"git status 2>&1 > out.txt",
		"git status >&out.txt",
		'echo \\"x; python -c 1',
		"echo 'a\\'; python -c 1; echo '",
		'echo "unterminated; python -c 1',
		"echo $'\\''; python -c 1; echo 'x'",
		'echo "a\\""; python -c 1',
		"grep 'x' f; python -c 1",
		"echo \\$'a\\'; python -c 1; echo ''",
		"ls >/dev/null/../x",
		"ls 2>/dev/nullx",
		// Before git 2.20, -l meant --create-reflog: this created a branch.
		"git branch -l zzz",
		"curl -d x=1 https://api",
		"curl -sSd x=1 https://api",
		"curl -dx=1 https://api",
		"curl --data x https://api",
		"curl --data-urlencode q=a https://api",
		"curl -F a=b https://api",
		"curl --form-string a=b https://api",
		"curl --json '{}' https://api",
		"curl -X POST https://api",
		"curl -XDELETE https://api",
		"curl --request=PUT https://api",
		"curl -D headers.txt https://api",
		"curl -c jar.txt https://api",
		"curl --trace log.txt https://api",
	])("%s is not safe", (command) => {
		expect(isSafeCommand(command)).toBe(false);
	});

	it.each([
		"fd -e ts src",
		"fd --hidden foo",
		"find . -name '*.ts'",
		"rg --pre-glob '*.gz' foo",
		"rg foo",
		"sort -u x",
		"sort -k2 -n x",
		"tree -L 2",
		"git remote",
		"git remote -v",
		"git remote show origin",
		"git remote get-url origin",
		"git branch",
		"git branch -a",
		"git branch -vv",
		"git branch --show-current",
		"git branch --list",
		"git diff",
		"git diff --stat",
		"git log --oneline",
		"curl -fsSL https://example.com",
		"curl -I https://example.com",
		"curl -X GET https://example.com",
		"curl -H 'x-d: y' https://example.com",
		"curl -D - https://example.com",
		"sed -n '1,20p' x",
		"sed -n '/error/p' x",
		"sed -n 's/foo/bar/p' x",
		"git branch --contains main",
		"git branch --list 'feat*'",
		"git branch -a --merged main",
		"git status 2>&1",
		"git status 2>/dev/null",
		"ls missing >/dev/null 2>&1",
		"rg foo &>/dev/null",
		"grep -E 'a|b' x",
		'grep "a;b" x',
		"echo 'a && b'",
	])("%s stays safe", (command) => {
		expect(isSafeCommand(command)).toBe(true);
	});
});
